-- AlterTable
ALTER TABLE `Match` MODIFY `phase` ENUM('GRUPOS','PLAYOFFS','OITAVAS','QUARTAS','SEMI','FINAL') NOT NULL;
ALTER TABLE `Round` MODIFY `phase` ENUM('GRUPOS','PLAYOFFS','OITAVAS','QUARTAS','SEMI','FINAL') NOT NULL;
