ALTER TABLE `User`
  MODIFY `status` ENUM('PENDENTE', 'ATIVO', 'RECUSADO', 'REMOVIDO') NOT NULL DEFAULT 'PENDENTE';

ALTER TABLE `BolaoMember`
  MODIFY `status` ENUM('PENDENTE', 'ATIVO', 'RECUSADO', 'REMOVIDO') NOT NULL DEFAULT 'PENDENTE';
